require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

RSpec/MultipleExpectations:
  Enabled: false
  
Style/Documentation:
  Enabled: false
