require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'

  TargetRubyVersion: 2.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rswag-ui.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/integration/**/*.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
