apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        app: app
        name: db
    spec:
      containers:
      - name: db
        image: postgres:13.2-alpine
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: TZ
            value: "Asia/Tokyo"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
