apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        app: app
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0-alpine
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
