---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/albums":
    get:
      summary: list albums
      tags:
      - Albums
      responses:
        '200':
          description: successful
    post:
      summary: create album
      tags:
      - Albums
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                release_year:
                  type: integer
                artist_id:
                  type: string
                genre_id:
                  type: string
              required:
              - title
              - genre_id
  "/api/v1/albums/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show album
      tags:
      - Albums
      responses:
        '200':
          description: successful
    patch:
      summary: update album
      tags:
      - Albums
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                release_year:
                  type: integer
                artist_id:
                  type: string
                genre_id:
                  type: string
    put:
      summary: update album
      tags:
      - Albums
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                release_year:
                  type: integer
                artist_id:
                  type: string
                genre_id:
                  type: string
    delete:
      summary: delete album
      tags:
      - Albums
      responses:
        '204':
          description: successful
  "/api/v1/artists":
    get:
      summary: list artists
      tags:
      - Artists
      responses:
        '200':
          description: successful
    post:
      summary: create artist
      tags:
      - Artists
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
  "/api/v1/artists/{artist_slug}":
    parameters:
    - name: artist_slug
      in: path
      description: artist's name
      required: true
      schema:
        type: string
    get:
      summary: show artist
      tags:
      - Artists
      responses:
        '200':
          description: successful
    patch:
      summary: update artist
      tags:
      - Artists
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
    put:
      summary: update artist
      tags:
      - Artists
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
    delete:
      summary: delete artist
      tags:
      - Artists
      responses:
        '204':
          description: successful
  "/api/v1/artists/{artist_slug}/albums":
    parameters:
    - name: artist_slug
      in: path
      description: artist's name
      required: true
      schema:
        type: string
    get:
      summary: list albums of an artist
      tags:
      - Artists
      responses:
        '200':
          description: successful
  "/api/v1/genres":
    get:
      summary: list genres
      tags:
      - Genres
      responses:
        '200':
          description: successful
  "/api/v1/jobs":
    get:
      summary: list jobs status
      tags:
      - Jobs
      responses:
        '200':
          description: successful
    post:
      summary: enqueue job
      tags:
      - Jobs
      parameters: []
      responses:
        '202':
          description: job enqueued
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                args:
                  type: array
                  items:
                    type: string
              required:
              - type
              - args
  "/api/v1/jobs/{jid}":
    parameters:
    - name: jid
      in: path
      description: jid
      required: true
      schema:
        type: string
    get:
      summary: show job status
      tags:
      - Jobs
      responses:
        '200':
          description: successful
    delete:
      summary: unschedule job
      tags:
      - Jobs
      responses:
        '204':
          description: job unscheduled
servers:
- url: "{scheme}://{defaultHost}"
  variables:
    scheme:
      default: http
    defaultHost:
      default: localhost:3377
