---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/assets":
    get:
      summary: list assets
      tags:
      - Assets
      responses:
        '200':
          description: successful
    post:
      summary: create asset
      tags:
      - Assets
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                genre_id:
                  type: string
              required:
              - title
              - genre_id
  "/api/v1/assets/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show asset
      tags:
      - Assets
      responses:
        '200':
          description: successful
    patch:
      summary: update asset
      tags:
      - Assets
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                genre_id:
                  type: string
    put:
      summary: update asset
      tags:
      - Assets
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                genre_id:
                  type: string
    delete:
      summary: delete asset
      tags:
      - Assets
      responses:
        '204':
          description: successful
  "/api/v1/genres":
    get:
      summary: list genres
      tags:
      - Genres
      responses:
        '200':
          description: successful
    post:
      summary: create genre
      tags:
      - Genres
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/genres/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show genre
      tags:
      - Genres
      responses:
        '200':
          description: successful
    patch:
      summary: update genre
      tags:
      - Genres
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    put:
      summary: update genre
      tags:
      - Genres
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    delete:
      summary: delete genre
      tags:
      - Genres
      responses:
        '204':
          description: successful
servers:
- url: "{scheme}://{defaultHost}"
  variables:
    scheme:
      default: http
    defaultHost:
      default: localhost:3377
