name: pipeline

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.0.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: bundle install
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3
      - name: Rubocop Lint
        run: bundle exec rubocop
  test:
      runs-on: ubuntu-latest
      services:
        db:
          image: postgres:13.2-alpine
          env:
            POSTGRES_HOST_AUTH_METHOD: 'trust'
          ports:
            - 5432:5432
      steps:
        - uses: actions/checkout@v1
        - name: Set up Ruby 3.0.0
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 3.0.0
        - name: bundle install
          run: |
            gem install bundler --no-document
            bundle install --jobs 4 --retry 3
        - name: Database Create
          run: |
            cp .github/database.yml config/database.yml
            bundle exec rails db:create db:migrate
          env:
            RAILS_ENV: test
        - name: Rspec Test
          run: bundle exec rspec
